app:
  name: "Golem"
  version: "0.1.0"
  log_level: "INFO"

vizdoom:
  # Path relative to the project root
  config_path: "conf/custom.cfg"
  # Built-in scenario name
  scenario_name: "basic.wad"
  resolution: "RES_640X480"
  episodes: 5
  
data:
  # Directory relative to project root
  output_dir: "data"
  filename_prefix: "doom_training_data"