app:
  name: "Golem"
  version: "0.2.3"
  log_level: "INFO"

keybindings:
  w: "+forward"
  s: "+back"
  a: "+moveleft"
  d: "+moveright"
  leftarrow: "+left"
  rightarrow: "+right"
  e: "+use"
  space: "+attack"

training:
  batch_size: 16
  learning_rate: 0.0001
  epochs: 10
  model_save_path: "data/golem_brain.pth"
  sequence_length: 32
  action_space_size: 8
  augmentation:
    mirror: true 

data:
  output_dir: "data"
  filename_prefix: "doom_training"

modules:
  basic:
    scenario: "basic.wad"
    config: "conf/common.cfg"
    episodes: 10
  
  navigation:
    scenario: "my_way_home.wad" 
    config: "conf/common.cfg"
    episodes: 10
    
  combat:
    scenario: "deadly_corridor.wad"
    config: "conf/common.cfg"
    episodes: 10

  doom:
    scenario: "/Users/gmoore/Home/games/doom/wads/DOOM.WAD"
    config: "conf/common.cfg"
    episodes: 1

  doom2:
    scenario: "/Users/gmoore/Home/games/doom/wads/DOOM2.WAD"
    config: "conf/common.cfg"
    episodes: 1

  plutonia:
    scenario: "/Users/gmoore/Home/games/doom/wads/PLUTONIA.WAD"
    config: "conf/common.cfg"
    episodes: 1

  tnt:
    scenario: "/Users/gmoore/Home/games/doom/wads/TNT.WAD"
    config: "conf/common.cfg"
    episodes: 1